version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: testing
          - DB_USERNAME: root
 
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: testing
 
    steps:
      - checkout
 
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql
 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
 
      - run: composer install -n --prefer-dist
 
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # npm
      - restore_cache:
          keys:
            - v1-node-{{ checksum "package.json" }}
            - v1-node-
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-node-{{ checksum "package.json" }}
    
      # npm run
      - restore_cache:
          keys:
            - v1-node-{{ checksum "package.json" }}
            - v1-node-
      - run: npm run dev
      - save_cache:
          paths:
            - ./node_modules
          key: v1-node-{{ checksum "package.json" }}
            
      - run: echo "APP_KEY=" > .env.testing
      - run: php artisan key:generate
      - run: php artisan migrate
 
      - run: ./vendor/bin/phpunit